AWSTemplateFormatVersion: '2010-09-09'
Description: Lab FortiEDR - VPC + EC2 Windows con AMI personalizada

Resources:
  FortiEDRVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: FortiEDR-VPC

  FortiEDRSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FortiEDRVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-west-1a

  FortiEDRInternetGateway:
    Type: AWS::EC2::InternetGateway

  FortiEDRVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FortiEDRVPC
      InternetGatewayId: !Ref FortiEDRInternetGateway

  FortiEDRRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FortiEDRVPC

  FortiEDRRoute:
    Type: AWS::EC2::Route
    DependsOn: FortiEDRVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref FortiEDRRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FortiEDRInternetGateway

  FortiEDRSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FortiEDRSubnet
      RouteTableId: !Ref FortiEDRRouteTable

  FortiEDRSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP
      VpcId: !Ref FortiEDRVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  FortiEDREC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.large
      ImageId: ami-0cdd0c1de5ebe61d1
      SubnetId: !Ref FortiEDRSubnet
      SecurityGroupIds:
        - !Ref FortiEDRSG
      Tags:
        - Key: Name
          Value: FortiEDR-Lab
        - Key: AutoDelete
          Value: 'true'

Outputs:
  InstanceId:
    Value: !Ref FortiEDREC2
    Description: EC2 Instance ID
  PublicIP:
    Value: !GetAtt FortiEDREC2.PublicIp
    Description: Public IP address
